---
type: docker
kind: pipeline
name: Build

trigger:
  event:
    include:
      - push
    exclude:
      - promote

steps:
  - name: Build & Publish Node Image
    image: plugins/docker
    settings:
      username: 4lch4
      password:
        from_secret: DOCKERHUB_TOKEN
      repo: 4lch4/node
      tags: latest
      dockerfile: ./Node/Dockerfile

  - name: Send Built Notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: 'The latest build of [4lch4/Koa-Oto](https://drone.4lch4.io/4lch4/Koa-Oto) was successful.'
