version: 3

tasks:
  pretty:
    aliases: [p, format, fmt]
    desc: Uses the Prettier CLI tool to format the codebase.
    cmds: ['prettier --write .']

  build:node:
    aliases: [bn]
    desc: Creates the parent docker image for Node with the Doppler CLI.
    cmds:
      - docker build -t 4lch4/node:latest -t 4lch4/1.2.0 ./Node

  push:node:
    aliases: [pn]
    desc: Pushes/publishes my built Docker image for NodeJS w/ the Doppler CLI to the Docker Hub.
    deps: [build:node]
    cmds:
      - docker push --all-tags 4lch4/node

  build:all:
    aliases: [ba]
    desc: Executes the build command for all of the Docker Images I provide.
    cmds:
      - task: build:node

  push:all:
    aliases: [pa]
    desc: Executes the push command for all of the Docker Images I provide.
    cmds:
      - task: push:node
