name: Build & Push Extended Node Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and Push Image
        uses: docker/build-push-action@v3
        with:
          context: ./Node
          push: true
          tags: 4lch4/node:latest,4lch4/node:1.0.0
