name: Build & Push Extended Node Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Taskfile CLI
        run: sudo snap install task --classic

      - name: Build Docker Image
        run: task build:node

      - name: Push/Publish Docker Image
        run: task push:node
