name: Build & Push Extended Node Docker Image

on:
  workflow_dispatch:
  push:

  # Run the job everyday at 08:00 UTC (02:00 CST).
  # This is to help ensure I always have the latest version of Node.
  schedule:
    - cron: 0 8 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v3
        with:
          context: ./Node
          push: true
          tags: 4lch4/node:latest,4lch4/node:1.2.0
